### ISSUE TITLE
鈴仙は＜臆病＞＜悲観的＞でいいのか？

### ISSUE THREAD

**Issue by wamekukyouzin** [wamekukyouzin/eratohoK#176]
ウルトラソニック眠り猫とかのくだりみてるとどうも臆病でも悲観的でもない気がする
むしろ楽観的とかつけてもいいくらいじゃないのか

**Comment by exli3141** [comment]
よくえーりんの実験台にされてる気はするから、そのあたりの諦めムードで悲観的な可能性はあるかもしれないですが、臆病ではないでしょうねぇ。
